#! /usr/bin/env bash
exec /home/miguelangel-garcia/miniconda3/envs/digital/bin/vvp -f "$0" "$@" <<'# EOF'
:ivl_version "13.0 (devel)" "(0_8-6859-gf50cc35d2-dirty)";
:ivl_delay_selection "TYPICAL";
:vpi_time_precision - 12;
:vpi_module "/home/miguelangel-garcia/miniconda3/envs/digital/lib/ivl/system.vpi";
:vpi_module "/home/miguelangel-garcia/miniconda3/envs/digital/lib/ivl/vhdl_sys.vpi";
:vpi_module "/home/miguelangel-garcia/miniconda3/envs/digital/lib/ivl/vhdl_textio.vpi";
:vpi_module "/home/miguelangel-garcia/miniconda3/envs/digital/lib/ivl/v2005_math.vpi";
:vpi_module "/home/miguelangel-garcia/miniconda3/envs/digital/lib/ivl/va_math.vpi";
S_0x1d12c8b0 .scope module, "shiftR_32_TB" "shiftR_32_TB" 2 4;
 .timescale -9 -12;
P_0x1d0f3550 .param/real "DUTY_CYCLE" 0 2 14, Cr<m4000000000000000gfc1>; value=0.500000
P_0x1d0f3590 .param/l "OFFSET" 0 2 15, +C4<00000000000000000000000000000000>;
P_0x1d0f35d0 .param/l "PERIOD" 0 2 13, +C4<00000000000000000000000000010100>;
v0x1d142fd0_0 .var "clk", 0 0;
v0x1d143090_0 .var "i", 2 0;
v0x1d143150_0 .net "n", 31 0, v0x1d119da0_0;  1 drivers
v0x1d143220_0 .var "rst", 0 0;
v0x1d1432f0_0 .var "sh", 0 0;
E_0x1d12b430 .event posedge, v0x1d119be0_0;
S_0x1d0f2140 .scope begin, "TEST_CASE" "TEST_CASE" 2 46, 2 46 0, S_0x1d12c8b0;
 .timescale -9 -12;
S_0x1d0f22d0 .scope module, "uut" "shiftR_32" 2 11, 3 1 0, S_0x1d12c8b0;
 .timescale 0 0;
    .port_info 0 /INPUT 1 "clk";
    .port_info 1 /INPUT 1 "sh";
    .port_info 2 /INPUT 1 "rst";
    .port_info 3 /OUTPUT 32 "n";
v0x1d119be0_0 .net "clk", 0 0, v0x1d142fd0_0;  1 drivers
v0x1d119da0_0 .var "n", 31 0;
v0x1d11a0f0_0 .net "rst", 0 0, v0x1d143220_0;  1 drivers
v0x1d11a300_0 .net "sh", 0 0, v0x1d1432f0_0;  1 drivers
E_0x1d0f2cf0 .event negedge, v0x1d119be0_0;
    .scope S_0x1d0f22d0;
T_0 ;
    %wait E_0x1d0f2cf0;
    %load/vec4 v0x1d11a0f0_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.0, 8;
    %pushi/vec4 32, 0, 32;
    %assign/vec4 v0x1d119da0_0, 0;
    %jmp T_0.1;
T_0.0 ;
    %load/vec4 v0x1d11a300_0;
    %flag_set/vec4 8;
    %jmp/0xz  T_0.2, 8;
    %pushi/vec4 0, 0, 1;
    %load/vec4 v0x1d119da0_0;
    %parti/s 31, 1, 2;
    %concat/vec4; draw_concat_vec4
    %assign/vec4 v0x1d119da0_0, 0;
    %jmp T_0.3;
T_0.2 ;
    %load/vec4 v0x1d119da0_0;
    %parti/s 31, 0, 2;
    %concati/vec4 0, 0, 1;
    %assign/vec4 v0x1d119da0_0, 0;
T_0.3 ;
T_0.1 ;
    %jmp T_0;
    .thread T_0;
    .scope S_0x1d12c8b0;
T_1 ;
    %delay 0, 0;
T_1.0 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x1d142fd0_0, 0, 1;
    %delay 10000, 0;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x1d142fd0_0, 0, 1;
    %delay 10000, 0;
    %jmp T_1.0;
T_1.1 ;
    %end;
    .thread T_1;
    .scope S_0x1d12c8b0;
T_2 ;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x1d143220_0, 0, 1;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x1d1432f0_0, 0, 1;
    %end;
    .thread T_2;
    .scope S_0x1d12c8b0;
T_3 ;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x1d143220_0, 0, 1;
    %wait E_0x1d12b430;
    %wait E_0x1d0f2cf0;
    %pushi/vec4 0, 0, 1;
    %store/vec4 v0x1d143220_0, 0, 1;
    %wait E_0x1d12b430;
    %wait E_0x1d0f2cf0;
    %pushi/vec4 1, 0, 1;
    %store/vec4 v0x1d1432f0_0, 0, 1;
    %pushi/vec4 0, 0, 3;
    %store/vec4 v0x1d143090_0, 0, 3;
T_3.0 ; Top of for-loop 
    %load/vec4 v0x1d143090_0;
    %pad/u 32;
    %cmpi/u 4, 0, 32;
    %jmp/0xz T_3.1, 5;
    %wait E_0x1d12b430;
T_3.2 ; for-loop step statement
    %load/vec4 v0x1d143090_0;
    %addi 1, 0, 3;
    %store/vec4 v0x1d143090_0, 0, 3;
    %jmp T_3.0;
T_3.1 ; for-loop exit label
    %end;
    .thread T_3;
    .scope S_0x1d12c8b0;
T_4 ;
    %fork t_1, S_0x1d0f2140;
    %jmp t_0;
    .scope S_0x1d0f2140;
t_1 ;
    %vpi_call 2 47 "$dumpfile", "shiftR_32_TB.vcd" {0 0 0};
    %vpi_call 2 48 "$dumpvars", 32'sb11111111111111111111111111111111, S_0x1d0f22d0 {0 0 0};
    %delay 1000000, 0;
    %vpi_call 2 49 "$finish" {0 0 0};
    %end;
    .scope S_0x1d12c8b0;
t_0 %join;
    %end;
    .thread T_4;
# The file index is used to find the file name in the following table.
:file_names 4;
    "N/A";
    "<interactive>";
    "shiftR_32_TB.v";
    "shiftR_32.v";
# EOF
